### ISSUE TITLE
Options for out data

### ISSUE THREAD

**Issue by kobzar** [wagoodman/diff2HtmlCompare#1]
Hi!
Thanks for greatest job.
This program very useful.
But do you can add options key, then i can see only diffs string in result ?

**Comment by wagoodman** [comment]
Thanks... glad it's useful for someone else!
Are you looking for a summarization feature? So if only 5 lines were changed in a 100 line file then the output would show the changed lines plus a few lines around them (about 15 lines or so)? Or were you talking about something else?

**Comment by kobzar** [comment]
I need something more than your script can.
I have two excel files wit three rows.
data field | number | phone number
And  i am need compare two files and get to out only strings, where data is different.
Not string by string compare :(

Your script is real awesome. But i am think, you most upgrade it to this option as i say...
Then more people will use it for stupid work :)
Thanks.

**Comment by wagoodman** [comment]
Ahh, I think I see your usecase. If you are attempting to compare two Excel files then excel does it for you: https://technet.microsoft.com/en-us/library/Dn205148.aspx

Though, excel 2010 doesn't have any comparison feature... so you need >=2013. I probably won't be adding the feature to compare excel files, but I believe it will work fine for CSV files as is.

**Comment by karthikjayapalu** [comment]
Hi,
Thanks for the script. it is helpful for me. i wanted to extend this script with few more use cases.
For eg: currently the output shows the diff between the html codes between two files. Wehre as i wanted to highlight the text, sequence difference between 2 files in a webpage format and not as a html code.  Could help me on how to go about it or if you have solution can you share it?

I will wait for your reply :-)
Thanks in Advance!!!
karthik

**Comment by wagoodman** [comment]
Hey! Sorry for the late response. I'd be happy to answer your question, but I don't quite follow with your use case yet: I think you may be asking how to show the difference between files without displaying the output in html --but I don't see the difference between what you're asking and the [unix diff utility](https://en.wikipedia.org/wiki/Diff_utility). Or maybe you're asking how to output text directly to the console instead of writing an `index.html` file?

**Comment by karthikjayapalu** [comment]
i have a QMS portal where in, the user have an option to export the QMS content in HTML format. use case is, if the users have 2 versions of the html exports and they want to see what is the difference between the two version. when they load the 2 versions of the content (HTML pages) side by side, the text difference, text alignment should be highlighted ( basically the 2 side by side window should not show the content as  HTML tags instead it should be normal webpages like how we see in the browser). I hope you can understand now. please let me know if still it is not clear.

**Comment by wagoodman** [comment]
Ok, I see what you're talking about: compare two html pages to see the content differences and not the html code differences. I think there are a few other options for you that would work better than this tool (or modifying this tool): 
- https://github.com/DaisyDiff/DaisyDiff
- https://www.changedetection.com/comparepages.html (not open source)

Let me know if this is what you're looking for!

**Comment by wagoodman** [comment]
It's been a while since there was a post here and I think those tools cover what you're looking for... closing this issue.
