### ISSUE TITLE
mmmh

### ISSUE THREAD

**Issue by kristall** [wagoodman/diff2HtmlCompare#4]
aloha,

the screenshot looks good, but no install script and no python3 support, so too much to do to get it working fast ...

**Comment by wagoodman** [comment]
So I took care of the low hanging fruit: I did a little clean up and also added python3 support. As for installation, I'm open for suggestions. Currently you can download the entire repository and run it as follows in the readme.md... so it's pretty standalone and doesn't tangle itself into the python site-packages directory or anything. What kind of way did you wish to install this (were you looking for the capability to `pip install` this?).

**Comment by kristall** [comment]
Thanks for the python3 support. After putting the "right" shebang (#!/usr/bin/env python3) the script worked fine. 

And my install issue was that the template was not part of code the as it now is, so now I agree that an install script is not needed.
